### ISSUE TITLE
Value cannot be null exception at startup

### ISSUE THREAD

**Issue by vivekdhami** [KevinJump/uSync#6] opened 2015-11-23 08:46 UTC
I am getting value can not be null exception at startup. As a result usync sync fails.

Following is the stack trace:
[ArgumentNullException: Value cannot be null.
Parameter name: value]
   System.Xml.Linq.XAttribute..ctor(XName name, Object value) +90525
   Umbraco.Core.Services.EntityXmlSerializer.Serialize(ILanguage language) +271
   Umbraco.Core.Services.PackagingService.Export(ILanguage language, Boolean raiseEvents) +156
   Jumoo.uSync.Core.Serializers.LanguageSerializer.SerializeCore(ILanguage item) +43
   Jumoo.uSync.Core.Serializers.LanguageSerializer.IsUpdate(XElement node) +214
   Jumoo.uSync.Core.Serializers.SyncBaseSerializer`1.DeSerialize(XElement node, Boolean forceUpdate) +50
   Jumoo.uSync.BackOffice.Handlers.LanguageHandler.Import(String filePath, Boolean force) +58
   Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates) +160
   Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportAll(String folder, Boolean force) +284
   Jumoo.uSync.BackOffice.uSyncBackOfficeContext.ImportAll(String folder, Boolean force) +451
   Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.Setup() +222
   Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) +141
   Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) +37
   Umbraco.Core.CoreBootManager.<Complete>b__8(IApplicationEventHandler x) +133
   Umbraco.Core.EnumerableExtensions.ForEach(IEnumerable`1 items, Action`1 action) +141
   Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete) +293
   Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete) +60
   Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e) +234
   Umbraco.Core.UmbracoApplicationBase.Application_Start(Object sender, EventArgs e) +9

[HttpException (0x80004005): Value cannot be null.
Parameter name: value]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +4467101
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +364
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +290

[HttpException (0x80004005): Value cannot be null.
Parameter name: value]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +4531288
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +94
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +191

**Comment by vivekdhami** [comment] 2015-11-23 10:11
2015-11-23 00:09:11,103 [P10444/D13/T12] INFO  Jumoo.uSync.BackOffice.Logging - Running Import: Languages
 2015-11-23 00:09:11,118 [P10444/D13/T12] ERROR Umbraco.Core.CoreBootManager - An error occurred running OnApplicationStarted for handler Jumoo.uSync.BackOffice.uSyncApplicationEventHandler
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Umbraco.Core.Services.EntityXmlSerializer.Serialize(ILanguage language)
   at Umbraco.Core.Services.PackagingService.Export(ILanguage language, Boolean raiseEvents)
   at Jumoo.uSync.Core.Serializers.LanguageSerializer.SerializeCore(ILanguage item)
   at Jumoo.uSync.Core.Serializers.LanguageSerializer.IsUpdate(XElement node)
   at Jumoo.uSync.Core.Serializers.SyncBaseSerializer`1.DeSerialize(XElement node, Boolean forceUpdate)
   at Jumoo.uSync.BackOffice.Handlers.LanguageHandler.Import(String filePath, Boolean force)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.Setup()
   at Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   at Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   at Umbraco.Core.CoreBootManager.<Complete>b__8(IApplicationEventHandler x)

**Comment by vivekdhami** [comment] 2015-11-23 10:29
Seems like an issue while syncing language items at startup. A migration problem probably from previous usync version to v3.0. Disabling LanguageGandler is a workaround for now.

**Comment by KevinJump** [comment] 2015-11-23 10:33
Hi, 

the umbracotracelog (in app_data/logs) might point to which language file is causing the fault, (you can also turn on debug in the config/log4net.config file and get a lot more debugging, 

If you can find which of your language files is causing the issue, i could have a look at reproducing it, and seeing what i can do. (at a guess i think it will be character encoding) 

what languages does your umbraco site have set up ?

**Comment by vivekdhami** [comment] 2015-11-23 10:53
Hi

I will turn on debug to see the exact cause. However if you look at the image below Language folder contains uSync files from previous version and uSync/Data/Languages contains the one from v3.0. 

![image](https://cloud.githubusercontent.com/assets/3636916/11334875/415b6034-91d8-11e5-8bea-a4a01eb3a994.png)

Somehow uSync is not generating files for all available languages.

Also this is the content of uSync/Data/Languages/enUS.config

<?xml version="1.0" encoding="utf-8"?>
<Language Id="1" CultureAlias="en-GB" FriendlyName="en-US" />

**Comment by vivekdhami** [comment] 2015-11-23 12:12
This is after enabling debug logs in log4net.config:

2015-11-23 12:08:39,634 [P5028/D21/T21] INFO  Jumoo.uSync.BackOffice.Logging - Running Import: Languages
 2015-11-23 12:08:39,634 [P5028/D21/T21] DEBUG Jumoo.uSync.BackOffice.uSyncAction - Getting Actions: for type Umbraco.Core.Models.ILanguage from 0 actions, found 0
 2015-11-23 12:08:39,649 [P5028/D21/T21] ERROR Umbraco.Core.CoreBootManager - An error occurred running OnApplicationStarted for handler Jumoo.uSync.BackOffice.uSyncApplicationEventHandler
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Umbraco.Core.Services.EntityXmlSerializer.Serialize(ILanguage language)
   at Umbraco.Core.Services.PackagingService.Export(ILanguage language, Boolean raiseEvents)
   at Jumoo.uSync.Core.Serializers.LanguageSerializer.SerializeCore(ILanguage item)
   at Jumoo.uSync.Core.Serializers.LanguageSerializer.IsUpdate(XElement node)
   at Jumoo.uSync.Core.Serializers.SyncBaseSerializer`1.DeSerialize(XElement node, Boolean forceUpdate)
   at Jumoo.uSync.BackOffice.Handlers.LanguageHandler.Import(String filePath, Boolean force)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.Setup()
   at Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   at Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   at Umbraco.Core.CoreBootManager.<Complete>b__8(IApplicationEventHandler x)
 2015-11-23 12:08:39,649 [P5028/D21/T21] DEBUG Umbraco.Core.CoreBootManager - Finished executing IApplicationEventHandler.OnApplicationStarted (took 5600ms)
 2015-11-23 12:08:39,649 [P5028/D21/T21] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at Umbraco.Core.Services.EntityXmlSerializer.Serialize(ILanguage language)
   at Umbraco.Core.Services.PackagingService.Export(ILanguage language, Boolean raiseEvents)
   at Jumoo.uSync.Core.Serializers.LanguageSerializer.SerializeCore(ILanguage item)
   at Jumoo.uSync.Core.Serializers.LanguageSerializer.IsUpdate(XElement node)
   at Jumoo.uSync.Core.Serializers.SyncBaseSerializer`1.DeSerialize(XElement node, Boolean forceUpdate)
   at Jumoo.uSync.BackOffice.Handlers.LanguageHandler.Import(String filePath, Boolean force)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.Setup()
   at Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   at Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   at Umbraco.Core.CoreBootManager.<Complete>b__8(IApplicationEventHandler x)
   at Umbraco.Core.EnumerableExtensions.ForEach[TItem](IEnumerable`1 items, Action`1 action)
   at Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete)
   at Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete)
   at Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
   at Umbraco.Core.UmbracoApplicationBase.Application_Start(Object sender, EventArgs e)

**Comment by KevinJump** [comment] 2015-12-04 10:54
Hi are you bringing the language files over from an older version of umbraco / uSync ? If so what version(s) ?

I've tried importing languages from v7.2.7 (usync 2.5) and its working for me :(

**Comment by ruant** [comment] 2017-09-22 13:31
I just removed the language folder, and it works as expected.
`enUS.config`
```
<?xml version="1.0" encoding="utf-8"?>
<Language Id="1" CultureAlias="nb" FriendlyName="en-US" />
```

Both export and import site run Umbraco 7.6.6

**Comment by KevinJump** [comment] 2017-09-22 15:06
Hi 

i wonder if this is a language conflict thing, 

I noticed that your language file is en-US but the alias is a Norwegian one? I will see if i can recreate it - but i think when you change the culture within an existing language umbraco doesn't update the name elements so you get this confused language thing.

**Comment by ruant** [comment] 2017-09-25 12:48
I wasn't the one setting this site, so I'm not 100% sure what has been done.  
But they mostly did it like you said, changing the culture.

If you need anything more from me let me know!

**Comment by KevinJump** [comment] 2018-03-02 12:03
Hi.
I'm closing this issue due to age & because i can't reproduce - it might have been fixed by something else, or an anomaly. If it is still happening, raise a new issue and it will be looked into.

**Closed** 2018-03-02 12:03 UTC
Labels: bug
