### ISSUE TITLE
Error deleting row from cmsPropertyData

### ISSUE THREAD

**Issue by heilc** [KevinJump/uSync#19] opened 2016-01-25 02:52 UTC
I am getting an error that is a little hard to reproduce but I think I can explain what is going on. Basically uSync is trying to delete a property type but is unable to because there are items in cmsPropertyData that are constraining it. These items have the gridview data for a page we started early in the project; later we removed the gridview but the entries in the database remained. uSync does not have a reference to this property on the content item anymore and must not be looking to remove the items in cmsPropertyData and running into the issue I have below.

Here is more information on the issue. On Import, uSync is throwing this error:

The DELETE statement conflicted with the REFERENCE constraint "FK_cmsPropertyData_cmsPropertyType_id". The conflict occurred in database "MyWebsite", table "dbo.cmsPropertyData", column 'propertytypeid'.
The statement has been terminated.

Running a sql trace I found this statement being executed:
exec sp_executesql N'SELECT *
FROM [cmsContentType]
INNER JOIN [umbracoNode]
ON [cmsContentType].[nodeId] = [umbracoNode].[id]
LEFT JOIN [cmsDocumentType]
ON [cmsDocumentType].[contentTypeNodeId] = [cmsContentType].[nodeId]
WHERE ([umbracoNode].[nodeObjectType] = @0)
AND ([umbracoNode].[parentID] = @1)
ORDER BY ([umbracoNode].[text])',N'@0 nvarchar(40),@1 int',@0=N'a2cb7800-f571-4787-9638-bc48539a0efb',@1=2601

There are 8 delete statements after this using sp_executesql. The delete statements remove all entries from the following tables where nodeId (or reference columns to) = 2601
umbracoUser2NodeNotify
umbracoUser2NodePermission
cmsTagRelationship
cmsContentTypeAllowedContentType
cmsContentTypeAllowedContentType
cmsContentType2ContentType
cmsContentType2ContentType
cmsPropertyType

It is this command that throws the error
exec sp_executesql N'DELETE FROM cmsPropertyType WHERE contentTypeId = @0',N'@0 int',@0=2601

Looking at the database, I can see the entry that the statement is trying to delete in [cmsPropertyType], and there are 4 entries in [cmsPropertyData] that use the [cmsPropertyType].[id] in their propertytypeid columns.

**Comment by KevinJump** [comment] 2016-01-27 09:52
Hi can this be deleted via the back office ? uSync doesn't actually go direct to the DB it goes via the core umbraco APIs so it's probably something inside the core - it's possible we are not calling the API in the right way. but my first check would be to see if umbraco can even delete something.

**Comment by ghost** [comment] 2016-01-27 14:11
I wouldn't be surprised considering the grid view is
still relatively new. Is there a way to catch these database errors cleanly
without stopping the sync to return the asp.net error page?  Something like
if "about page" in my content tree fails to sync I see a red x in the
report and the sql error message in the details but the rest of the sync
carries on. Then I would know where to look. Or if my co-workers are working on something else and did a get latest, they will be able to continue work and notify me that the "about page" is broken.

**Comment by KevinJump** [comment] 2018-03-02 12:01
Hi.
I'm closing this issue due to age & because i can't reproduce - it might have been fixed by something else, or an anomaly. If it is still happening, raise a new issue and it will be looked into.

**Closed by KevinJump** 2018-03-02 12:01 UTC
